fn main() {
    cbindgen::Builder::new()
        .with_crate(".")
        .with_language(cbindgen::Language::C)
        .with_autogen_warning("/* Generated by cbindgen, do not edit */")
        .generate()
        .unwrap()
        .write_to_file("icebox.h");
}
