[package]
name = "icebox_backend_dumb_dump"
version = "0.1.0"
edition = "2018"

[features]
std = ["ibc/std"]

[dependencies]
ibc = {path = "../icebox_core", package = "icebox_core"}
kvm-common = {path = "../kvm-common"}

bytemuck = {version = "1.7", features = ["derive"]}
